export const projects = [
	{
		title: 'M Lab Studio',
		description: 'Portfolio of the company where I am working right now, worth watching!',
		image: { webp: '/images/mlab.webp', jpg: '/images/mlab.jpg' },
		company: 'M Lab Studio',
		source: 'https://mlab-studio.com/',
		category: 'M Lab Studio',
		id: 6,
	},
	{
		title: 'Tiska Fabrics',
		description: 'Web store with custom pattern generator for fabrics and beautiful Frontend.',
		image: { webp: '/images/tiska.webp', jpg: '/images/tiska.jpg' },
		company: 'PopArt Studio',
		source: 'https://tiskafabrics.com/',
		category: 'PopArt Studio',
		id: 5,
	},
	{
		title: 'Live Radio Stations',
		description: 'Interactive web app with radio stations and build in music player (SPA).',
		image: { webp: '/images/lrs.webp', jpg: '/images/lrs.jpg' },
		company: 'M Lab Studio',
		source: 'https://liveradiostations.net/',
		category: 'M Lab Studio',
		id: 4,
	},
	{
		title: 'Fazer Agency',
		description: 'One of the projects from the company I worked on, custom theme development.',
		image: { webp: '/images/fazer.webp', jpg: '/images/fazer.jpg' },
		company: 'PopArt Studio',
		source: 'https://fazer.agency/',
		category: 'PopArt Studio',
		id: 3,
	},
	{
		title: 'Edward Austin',
		description: 'One of the projects from the company I worked on, during my internship.',
		image: { webp: '/images/austin.webp', jpg: '/images/austin.jpg' },
		company: 'PopArt Studio',
		source: 'https://www.edward-austin.com/',
		category: 'PopArt Studio',
		id: 2,
	},
	{
		title: 'Heri Transporte DE',
		description: 'This project is part of freelance, the designer created the design and I did the development part.',
		image: { webp: '/images/heri.webp', jpg: '/images/heri.jpg' },
		company: 'Reference project',
		source: 'https://heri-transporte.de/',
		category: 'Personal',
		id: 1,
	},
	{
		title: 'EssentialGHIB',
		description: 'Simple landing page, fully created by me for Upwork customer during my early days in industry.',
		image: { webp: '/images/eghib.webp', jpg: '/images/eghib.jpg' },
		company: 'Upwork freelance',
		source: 'https://www.essentialghib.com/',
		visit: 'https://github.com/Aleksa21000/EssentialGHIB',
		category: 'Personal',
		id: 0,
	},
];

export const TimeLineData = [
	{ year: 2019, text: 'Started my journey in Wespero web studio' },
	{ year: 2021, text: 'Second full time job at PopArt Studio' },
	{ year: 2022, text: 'Got promoted to Software Engineer at PopArt Studio' },
	{ year: 2023, text: 'Started part time job at M Lab Studio (9 months) as Software Engineer' },
	{ year: 2023, text: 'Started full time job at M Lab Studio (January) as Software Engineer' },
];

export const profileImages = { webp: '/images/profile-picture.webp', jpg: '/images/profile-picture.jpg' };
